---
- hosts: all
  sudo: yes

  vars:
    gluster_mount_dir: /glusterfs
    gluster_brick_dir: /glusterfs/replica
    gluster_brick_name: vol_replica
    highload_somaxconn: '3240000'
    highload_rmem_max: '167772160'
    highload_wmem_max: '167772160'
    highload_rmem_default: '167772160'
    highload_wmem_default: '167772160'
    highload_optmem_max: '2048000'
    highload_tcp_rmem: '1024000 8738000 1677721600'
    highload_tcp_wmem: '1024000 8738000 1677721600'
    highload_tcp_mem: '1024000 8738000 1677721600'
    highload_udp_mem: '1024000 8738000 1677721600'
    highload_ip_local_port_range: "1025 65000"
    highload_tcp_window_scaling: '1' 
    highload_tcp_tw_reuse: '1'
    highload_tcp_tw_recycle: '0'
    highload_tcp_timestamps: '1'
    highload_tcp_sack: '1'
    highload_tcp_keepalive_intvl: 30
    highload_tcp_keepalive_probes: 5
    highload_netdev_max_backlog: '50000'
    highload_tcp_max_syn_backlog: '3240000'
    highload_tcp_max_tw_buckets: '1440000'
    highload_tcp_fin_timeout: '15'  
    highload_tcp_slow_start_after_idle: '0'
    highload_tcp_congestion_control: 'cubic'
    highload_tcp_synack_retries: '1'
    highload_tcp_max_orphans: '400000'
    highload_udp_rmem_min: '8192'
    highload_udp_wmem_min: '8192'
    highload_tune_udp: false
    highload_limits_nofile: 500000
    highload_fs_file_max: 10000000
    highload_nf_conntrack_max: 1000000
    highload_vm_max_map_count: 262144

  roles:
    - geerlingguy.glusterfs

  tasks:
    - name: Ensure Gluster brick and mount directories exist.
      file: "path={{ item }} state=directory mode=0775"
      with_items:
        - "{{ gluster_brick_dir }}"
        - "{{ gluster_mount_dir }}"

    - name: Configure Gluster volume.
      gluster_volume:
        state: present
        name: "{{ gluster_brick_name }}"
        brick: "{{ gluster_brick_dir }}"
        replicas: 2
        cluster: "{{ groups.gluster | join(',') }}"
        host: "{{ inventory_hostname }}"
        options:
          performance.write-behind: 'on'
          storage.batch-fsync-delay-usec: '0'
          performance.client-io-threads: 'on'
          network.frame-timeout: '60'
          performance.quick-read: 'on'
          cluster.quorum-type: 'fixed'
          cluster.quorum-count: '1'
          performance.read-ahead: 'off'
          performance.cache-size: '256MB'
          performance.io-thread-count: '64'
          performance.high-prio-threads: '64'
          performance.normal-prio-threads: '64'
          network.ping-timeout: '5'
          server.event-threads: '16'
          client.event-threads: '16'
        force: yes
      run_once: true

    - name: Stop and disable NFS server if one exists
      service:
        name: nfs-server
        state: stopped
        enabled: false
      ignore_errors: true
      tags:
        - manage_existing_nfs
    
    - name: create /etc/sysctl.d directory
      file: path=/etc/sysctl.d state=directory

    - sysctl: name="net.core.somaxconn" value={{ highload_somaxconn }} sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
    - sysctl: name="net.core.rmem_max" value={{ highload_rmem_max }} sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
    - sysctl: name="net.core.wmem_max" value={{ highload_wmem_max }} sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
    - sysctl: name="net.core.rmem_default" value={{ highload_rmem_default }} sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
    - sysctl: name="net.core.wmem_default" value={{ highload_wmem_default }} sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
    - sysctl: name="net.core.optmem_max" value={{ highload_optmem_max }} sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
    - sysctl: name="net.ipv4.tcp_rmem" value="{{ highload_tcp_rmem }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
    - sysctl: name="net.ipv4.tcp_wmem" value="{{ highload_tcp_wmem }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
    - sysctl: name="net.ipv4.tcp_mem" value="{{ highload_tcp_mem }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
    - sysctl: name="net.ipv4.udp_mem" value="{{ highload_udp_mem }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf

    - sysctl: name="net.ipv4.ip_local_port_range" value="{{ highload_ip_local_port_range }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
    - sysctl: name="net.ipv4.tcp_tw_reuse" value="{{ highload_tcp_tw_reuse }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf

    - sysctl: name="net.core.netdev_max_backlog" value="{{ highload_netdev_max_backlog }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
    - sysctl: name="net.ipv4.tcp_max_syn_backlog" value="{{ highload_tcp_max_syn_backlog }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
    - sysctl: name="net.ipv4.tcp_max_tw_buckets" value="{{ highload_tcp_max_tw_buckets }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
    - sysctl: name="net.ipv4.tcp_fin_timeout" value="{{ highload_tcp_fin_timeout }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf

    - sysctl: name="net.ipv4.tcp_slow_start_after_idle" value="{{ highload_tcp_slow_start_after_idle }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
    - sysctl: name="net.ipv4.tcp_window_scaling" value="{{ highload_tcp_window_scaling }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
    - sysctl: name="net.ipv4.tcp_timestamps" value="{{ highload_tcp_timestamps }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
    - sysctl: name="net.ipv4.tcp_sack" value="{{ highload_tcp_sack }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
    - sysctl: name="net.ipv4.tcp_keepalive_intvl" value="{{ highload_tcp_keepalive_intvl }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
    - sysctl: name="net.ipv4.tcp_keepalive_probes" value="{{ highload_tcp_keepalive_probes }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
    - sysctl: name="net.ipv4.tcp_synack_retries" value="{{ highload_tcp_synack_retries }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
    - sysctl: name="net.ipv4.tcp_max_orphans" value="{{ highload_tcp_max_orphans }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf

    - modprobe:
        name: tcp_cubic
        state: present
    - modprobe:
        name: ip_conntrack
        state: present    

    - sysctl: name="net.ipv4.tcp_congestion_control" value="{{ highload_tcp_congestion_control }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
    - sysctl: name="fs.file-max" value="{{ highload_fs_file_max }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf

    - sysctl: name="net.ipv4.udp_rmem_min" value="{{ highload_udp_rmem_min }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
    - sysctl: name="net.ipv4.udp_wmem_min" value="{{ highload_udp_wmem_min }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
  
    - pam_limits:
        domain: '{{ item }}'
        limit_type: '-'
        limit_item: nofile
        value: '{{ highload_limits_nofile }}'
      with_items:
        - '*'
        - 'root'
        - 'nginx'

    - sysctl: name="net.nf_conntrack_max" value="{{ highload_nf_conntrack_max }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf
    - sysctl: name="vm.max_map_count" value="{{ highload_vm_max_map_count }}" sysctl_set=yes sysctl_file=/etc/sysctl.d/highload.conf 